quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/BookingApp
quarkus.datasource.username=postgres
quarkus.datasource.password=admin


quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, POST, PUT, DELETE
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true
quarkus.hibernate-orm.database.generation=update


quarkus.flyway.migrate-at-start=true
quarkus.flyway.out-of-order=true
quarkus.flyway.baseline-on-migrate=true


recaptcha.secret-key=6LfeRqwrAAAAABY4yZJFtB79e2mpfG1_L70WTU39
recaptcha.url=https://www.google.com/recaptcha/api/siteverify

token.private-key-path=privateKey.pem 
token.public-key-path=publicKey.pem
token.issuer=BookingApp
mp.jwt.verify.publickey.location=/publicKey.pem
mp.jwt.verify.issuer=BookingApp